app:
  name: Fusion
  env: dev

server:
  host: 0.0.0.0
  port: 8080
  read_timeout: 30s
  write_timeout: 30s

database:
  host: localhost
  port: 5432
  user: postgres
  password: 123456
  name: fusion
  ssl_mode: disable
  migrate:
    auto_migrate: true
    source: 'file://./migrations'

logger:
  level: info
  enable_console: true
  enable_file: false
  console_color: true

  fx:
    enable: false

job:
  broadcast_reminder:
    enable: true
    cron_expr: '*/1 * * * *'
